### ISSUE TITLE
App not compiling - undefined is not an object

### ISSUE THREAD

**Issue by VITivant** [marklawlor/nativewind#294] opened 2022-10-24 13:47 UTC
**Describe the bug**
Today I started getting an error undefined is not an object (evaluating '_NativeWindStyleSheet.create')

I have ended up setting up a new project to try and reproduce and have been getting the same error.

1st I tried an expo starter with typescript & navigation (npx create-expo-app) - got an immediate fail
2nd I tried to use the expo example on this GitHub - was fine for a bit until again same error. 

**To Reproduce**
1. Expo start - using Expo Go on Android
2. See error (screenshot attached below)

**Expected behavior**
App should load - error occurs on load

**Expo Snack**
See screenshot below, app no longer loads

**Screenshots**
https://files.slack.com/files-pri/T03NA4YL5A7-F048FFJNBQQ/screenshot_20221024-160658_expo_go.jpg

**Additional context**
None

**Comment by marklawlor** [comment] 2022-10-24 21:01
Duplicate of #286

**Closed by marklawlor** 2022-10-24 21:01 UTC
