### ISSUE TITLE
Auto styled Babel not working with react-native-paper

### ISSUE THREAD

**Issue by UchihaSV** [marklawlor/nativewind#692] opened 2023-12-06 21:05 UTC
Hello i'm use React-Native 0.72.* version and try install and use NativeWind v2 as in your examples(https://www.nativewind.dev/quick-starts/react-native-cli):
1) use `npm i nativewind` and `npm i -D tailwindcss` (yes i use npm, not yarn)
2) run `npx tailwindcss init` and edited `tailwind.config.js` to write my src dir
3) added: `plugins: ["nativewind/babel"]` in my `babel.config.js`
4) run `npm start` in android emulator and className not work in any components.

I'm tried use className on View or Text imported from "react-native".

I think maybe conflict with my react-native-paper 5.11.* which too use babel config:
 `env: {production: {plugins: ['react-native-paper/babel']}}`

Please help to solve this problem.

**Comment by marklawlor** [comment] 2024-02-14 05:44
I'm going to close this issue as I cannot assist you without a copy of your repo. There's a high change that something was incorrectly configured, but since I can't see your code, I can't provide any assistance.

If you reply with a reproduction of your issue then I'm happy to reopen and assist you

**Closed by marklawlor** 2024-02-14 05:44 UTC
