### ISSUE TITLE
[ERROR] Use process(css).then(cb) to work with async plugins

### ISSUE THREAD

**Issue by chamaldesilva** [marklawlor/nativewind#501] opened 2023-07-14 08:03 UTC
This is the error I got after installing and configuring nativewind library with RN 0.72.3

`error: App.js: /Users/***/Developer/***/App.js: Use process(css).then(cb) to work with async plugins`

**Comment by rdlogout** [comment] 2023-07-14 09:22
same 

> This is the error I got after installing and configuring nativewind library with RN 0.72.3
> 
> `error: App.js: /Users/***/Developer/***/App.js: Use process(css).then(cb) to work with async plugins`

same following the official guide

**Comment by chamaldesilva** [comment] 2023-07-14 09:27
> same
> 
> > This is the error I got after installing and configuring nativewind library with RN 0.72.3
> > `error: App.js: /Users/***/Developer/***/App.js: Use process(css).then(cb) to work with async plugins`
> 
> same following the official guide

Finally, I was able to find the root cause. This is because of the tailwindcss library.

**Comment by AbdulHakkam** [comment] 2023-07-14 10:27
> > same
> > > This is the error I got after installing and configuring nativewind library with RN 0.72.3
> > > `error: App.js: /Users/***/Developer/***/App.js: Use process(css).then(cb) to work with async plugins`
> > 
> > 
> > same following the official guide
> 
> Finally, I was able to find the root cause. This is because of the tailwindcss library.

Had the same issue, was able to fix it by adding ```plugins: [['nativewind/babel', {mode: 'transformOnly'}]],``` to my ```babel.config.js```.

**Comment by kenjimaeda54** [comment] 2023-07-14 11:40
I am with this error, how resolve?

**Comment by AbdulHakkam** [comment] 2023-07-14 11:47
> I am with this error, how resolve?

Change your tailwind version to ```3.3.2``` in your ```package.json``` and run yarn/npm install

**Comment by vahid1995** [comment] 2023-07-14 12:07
> > I am with this error, how resolve?
> 
> Change your tailwind version to `3.3.2` in your `package.json` and run yarn/npm install

thanks men!

**Comment by Santy1422** [comment] 2023-07-14 13:04
me too

**Comment by chamaldesilva** [comment] 2023-07-14 13:05
> > > I am with this error, how resolve?
> > 
> > 
> > Change your tailwind version to `3.3.2` in your `package.json` and run yarn/npm install
> 
> <img alt="Screenshot 2023-07-14 at 5 48 56 PM" width="1439" src="https://user-images.githubusercontent.com/12225335/253575416-aaf83eb5-4167-4277-9892-fbe295599bb2.png">
> @AbdulHakkam I changed it to 3.3.2 but still facing this issue.

1. keep the version to 3.3.2
2. clean the ios build and delete the Pods folder
3. delete ios Derived data
4. delete the node_modules and reinstall
5. run the pod install
6. run the app

**Comment by chamaldesilva** [comment] 2023-07-14 13:08
Install `nativewind` using the following scripts.

```
yard add nativewind
yarn add --dev tailwindcss@3.3.2
```

**Comment by ihassanamjad** [comment] 2023-07-14 13:09
Working fine now. Thanks @chamaldesilva 💯

**Comment by Santy1422** [comment] 2023-07-14 13:12
before working every nigth     "tailwindcss": "^3.2.0"

**Comment by 0xjcr** [comment] 2023-07-14 16:16
> > > > I am with this error, how resolve?
> > > 
> > > 
> > > Change your tailwind version to `3.3.2` in your `package.json` and run yarn/npm install
> > 
> > 
> > <img alt="Screenshot 2023-07-14 at 5 48 56 PM" width="1439" src="https://user-images.githubusercontent.com/12225335/253575416-aaf83eb5-4167-4277-9892-fbe295599bb2.png">
> > @AbdulHakkam I changed it to 3.3.2 but still facing this issue.
> 
> 1. keep the version to 3.3.2
> 2. clean the ios build and delete the Pods folder
> 3. delete ios Derived data
> 4. delete the node_modules and reinstall
> 5. run the pod install
> 6. run the app

Could you please explain step 2,3 and 5?

**Comment by alanmartinez24** [comment] 2023-07-14 16:21
@0xjcr - In fact, it's not required to rebuild the app because Nativewind/tailwindcss are JS only libraries.

What you have to do is modify `package.json` to update `tailwindcss` version to `3.3.2`(Based on my experience `3.3.3` didn't work), and then run `npm install` or `yarn install`, and then restart the app. Hope it helps.

**Comment by 0xjcr** [comment] 2023-07-14 16:54
@alanmartinez24 Thank you for the reply. Actually I tried this though and still encountered the same errror.

**Comment by alanmartinez24** [comment] 2023-07-14 16:57
@0xjcr Show me your package.json

**Comment by 0xjcr** [comment] 2023-07-14 16:57
{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.18",
    "expo-status-bar": "~1.4.4",
    "nativewind": "^2.0.11",
    "postcss-loader": "^4.2.0",
    "react": "18.2.0",
    "react-native": "0.71.8"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "tailwindcss": "^3.3.2"
  },
  "private": true
}

**Comment by alanmartinez24** [comment] 2023-07-14 16:58
Update `^3.3.2` to `3.3.2`

**Comment by 0xjcr** [comment] 2023-07-14 17:01
👑 I think you dropped this. Thank you

**Comment by DataHawker** [comment] 2023-07-14 17:06
I was in the same boat yesterday for 5 hours. I reset how I checked all my packages for ^ and ~ files last night now but still got me chasing a rabbit looking at plugin issues.... It would be great if after NPM install, you can see a list of just the packages that were installed/updated vs "1 package changed". Breaking change in nativewind between 3.3.2 and 3.3.3....

**Comment by parveezahamed** [comment] 2023-07-14 17:34
> Update `^3.3.2` to `3.3.2`

Thank you; worked :)

**Comment by rashaangriffith-es** [comment] 2023-07-14 18:50
> > I am with this error, how resolve?
> 
> Change your tailwind version to `3.3.2` in your `package.json` and run yarn/npm install


> > Update `^3.3.2` to `3.3.2`
> 
> Thank you; worked :)

Been working on this for almost 24 hours.  Thank you!!!!

**Comment by Kite2002** [comment] 2023-07-14 19:41
Will there be compatibility with 3.3.3 in the future ? what's causing this ?

**Comment by sergiosrtd** [comment] 2023-07-15 00:08
> Update `^3.3.2` to `3.3.2`

This worked for me, thank you

**Comment by dalley8626** [comment] 2023-07-16 07:03
For some reason still not working for me

```
"dependencies": {
    "@apollo/client": "^3.7.16",
    "@expo/vector-icons": "^13.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~49.0.3",
    "expo-constants": "~14.4.2",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "graphql": "^16.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6",
    "nativewind": "^2.0.11"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "dotenv": "^16.3.1",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3",
    "tailwindcss": "3.3.2"
  },
  "overrides": {
    "react-refresh": "~0.14.0"
  },
  "resolutions": {
    "react-refresh": "~0.14.0"
  },
  "private": true
}

```

**Comment by DataHawker** [comment] 2023-07-16 12:54
You can delete package-lock and your node-mod folder(s). 'npm install' again and it should work.

**Comment by dalley8626** [comment] 2023-07-16 15:10
Thanks man, worked now

**Comment by codemile** [comment] 2023-07-19 12:40
I believe this is related to a recent change in Tailwind `3.3.3` to use async/wait in the PostCSS plugin.

See PR: https://github.com/tailwindlabs/tailwindcss/pull/11548

I've never looked at the NativeWind code before, but upon an a quick browsing of the code. I have an idea that it might be necessary to match the async/wait approach in the NativeWind PostCSS plugin as it calls the TailwindCSS plugin internally.

See code reference: https://github.com/marklawlor/nativewind/blob/ece93a6db8730c01b1df9f39eb44ee590714fbd7/packages/nativewind/src/postcss/extract-styles.ts#L26

In particular, this appears to be the offending line of code

```
postcss(plugins).process(cssInput).css;
```

I would assume the entire call stack needs to be switched to async that calls `extraStycles`.

I would open a PR to fix this, but opening a code refactoring as my first PR isn't always welcomed on a project and seems to me that NativeWind was last tested against Tailwind 3.2. So I would need to bump the dependency to `3.3.3` and force everyone to upgrade.

Let me know if this was helpful.

**Comment by devilGhostman** [comment] 2023-07-19 15:33
> This is the error I got after installing and configuring nativewind library with RN 0.72.3
> 
> `error: App.js: /Users/***/Developer/***/App.js: Use process(css).then(cb) to work with async plugins`

this error is because of tailwind you need to change tailwind version from 3.3.3 to 3.3.2.All you need to do is remove node_modules folder and package-lock.json file and tailwind from package.json file and then 
```shell
npm install --dev tailwindcss@3.3.2
```

**Comment by rizaldiariif** [comment] 2023-07-25 10:26
guys can you give me an example repository where it is using expo-router and nativewind. but the catch is it is really working. because I already followed the official guide and downgraded the tailwind to `3.3.2`. but it still has this error.

```
Web Bundling failed 271ms
Unable to resolve "../styles.css" from "app\_layout.tsx"
```

**Comment by hqasmei** [comment] 2023-07-29 21:20
Has anyone been able to solve this?

**Comment by guillermoST** [comment] 2023-08-08 09:24
We were running into the same issue.. 

I had to change the tailwind.config.js to a new tailwind.config.ts with an asynctheme.

Have a look at https://github.com/sramam/zz-tailwind-config-async/blob/main/tailwind.config.ts#L41

I migrated the example into our codebase, and it all seems to work now.

**Comment by reuel88** [comment] 2023-08-20 17:44
It is working for me. But once I move it into a monorepo the error returns. Can anyone find the root of this problem?

apps/app-mobile-client/package.json
```{
  "name": "app-mobile-client",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.7",
    "expo-status-bar": "~1.6.0",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "expo-router": "2.0.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "expo-linking": "~5.0.2",
    "expo-constants": "~14.4.2",
    "react-native-gesture-handler": "~2.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "autoprefixer": "^10.4.15",
    "postcss": "^8.4.28",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

**Comment by marklawlor** [comment] 2023-08-21 07:02
@reuel88 You need to pin the version, you still have a version range in your package.json

```diff
- "tailwindcss": "^3.3.2",
+ "tailwindcss": "3.3.2",
```

**Comment by marklawlor** [comment] 2023-08-21 07:06
Duplicate of https://github.com/marklawlor/nativewind/issues/498

**Closed by marklawlor** 2023-08-21 07:06 UTC

**Comment by Callmesammy** [comment] 2023-09-18 13:24
> @reuel88 You need to pin the version, you still have a version range in your package.json
> 
> ```diff
> - "tailwindcss": "^3.3.2",
> + "tailwindcss": "3.3.2",
> ```

it worked ..... thanks

**Comment by riverhouse-device** [comment] 2024-04-19 07:42
> > I am with this error, how resolve?
> 
> Change your tailwind version to `3.3.2` in your `package.json` and run yarn/npm install

i have already installed this version.but same issue i am facing

**Comment by Hitesh025** [comment] 2024-04-19 07:44
> > I am with this error, how resolve?
> 
> Change your tailwind version to `3.3.2` in your `package.json` and run yarn/npm install

did the same thing,but after that same error i am facing

**Comment by thmthu** [comment] 2024-04-26 01:22
what is the version of Node JS you use for this prj? i also face the same error although i use 3.3.2

**Comment by Hitesh025** [comment] 2024-04-26 02:07
I create the project on v16.18.0 but currently using v20.12.0

**Comment by TechsolutionAAA** [comment] 2024-09-09 05:33
yarn add --dev tailwindcss@3.3.2

It is working well. 

Thanks man !

**Comment by Reqima-dev** [comment] 2024-09-29 19:51
> Update `^3.3.2` to `3.3.2`

It is working well.

Thanks man !
