### ISSUE TITLE
Typescript: Property className does not exist on ImageBackground

### ISSUE THREAD

**Issue by sawariz0r** [marklawlor/nativewind#124] opened 2022-07-20 16:35 UTC
**Describe the bug**
Declaring className on an ImageBackground gives me some sweet red squiggly lines, but it works as expected still. So probably just a type error. 

Happy to provide a PR if I manage to find a solution

**To Reproduce**
1. Use ImageBackground from react-native
2. Declare prop "className" 
3. Get squiggly lines and type error

**Expected behavior**
It works as expected, but it would be sweet if I didn't have to use ts-ignores

**Screenshots**
![Screenshot 2022-07-20 at 18 33 52](https://user-images.githubusercontent.com/17275925/180035860-f2456cda-dccf-42e3-89fb-d20e4939a241.png)

**Comment by marklawlor** [comment] 2022-07-20 18:45
Fixed on `latest`, thanks for reporting 👍

**Closed by marklawlor** 2022-07-20 18:45 UTC

**Comment by chaosLegacy** [comment] 2022-09-04 16:40
Hi,
Thank you so much for this great package :) 
I'm allowing myself to reopen this issue because I couldn't understand why visual code shows red squiggly lines on any components I add to my code. 
The style is working perfectly as expected, it's just the errors in visual code that are annoying
For the steps, they are the same steps as mentioned by @sawariz0r 

To Reproduce
Steps to reproduce the behavior:

Add any components from react-native
Declare prop "className"
Get squiggly lines and type error

Expected behavior
It works as expected

![image](https://user-images.githubusercontent.com/11313734/188323922-313ec245-cd0d-4437-982b-d1c797617d8b.png)
