### ISSUE TITLE
v3: A never finished building

### ISSUE THREAD

**Issue by chenhb23** [marklawlor/nativewind#363] opened 2022-12-14 02:55 UTC
**Describe the bug**
building stuck on Done copying assets when i use `withNativewind(config)`

**To Reproduce**

run on xcode

**Screenshots**

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/74194963/207492926-2a5119de-dbef-46f1-a4d8-e97de7a24326.png">

**Additional context**

```js
const {getDefaultConfig} = require('metro-config')
const withNativewind = require('nativewind/metro')

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig()

  const config = {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  }

  // return withNativewind(config) // stuck ❌
  return config // build success ✅
})()
```

**Comment by chenhb23** [comment] 2022-12-14 03:43
`metro.config.js` and  `nativewind/metro`'s `NODE_ENV` are different

<img width="799" alt="image" src="https://user-images.githubusercontent.com/74194963/207499562-52b76322-f6c7-4350-a82f-f47340a60ebb.png">

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/74194963/207499751-ff067408-4904-42b7-9dd5-90d39035b42a.png">


<img width="1144" alt="image" src="https://user-images.githubusercontent.com/74194963/207499402-e1486444-2a97-44a9-a5c2-d42250729ea7.png">

**Comment by fendyk** [comment] 2022-12-15 11:02
Maybe wrap it like this example:

```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const withNativewind = require("nativewind/metro");

module.exports = withNativewind({
    transformer: {
        getTransformOptions: async () => ({
            transform: {
                experimentalImportSupport: false,
                inlineRequires: true,
            },
        }),
    },
});
```

**Comment by allpwrfulroot** [comment] 2022-12-18 23:45
Took me a minute, but: 

```
const { getDefaultConfig } = require('metro-config');
const withNativewind = require('nativewind/metro');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  const config = {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
  return withNativewind(config);
})();
```

Works for me, perhaps as simple as ordering within the transformer field? Or the async getTransformOptions

**Comment by tehfailsafe** [comment] 2023-01-08 23:17
I'm running into this issue as well, although some of these options look like the work locally, they never build with `eas build`... One thing I noticed is all the solutions seem to have the same issue in the logs, the `Nativewind: Rebuilding...` step never completes before the `bundling complete` message.

![image](https://user-images.githubusercontent.com/1388454/211223965-43a32c06-0d74-46e9-9932-8ea4925816f7.png)


They all stop at varying levels of complete, 20%, 50% etc. But in all my tests they never get to 100% before the bundle is complete.

**Comment by marklawlor** [comment] 2023-01-08 23:22
"Rebuilding" is different to the originally reported error "Done copying assets".  Can you please share your `tailwind.config.js` and ensure you are not including the `node_modules` inside your `content` paths

**Comment by tehfailsafe** [comment] 2023-01-08 23:23
```
/** @type {import('tailwindcss').Config} */
const nativewind = require("nativewind/tailwind");

module.exports = {
  content: ["./App.tsx", "./src/**/*.tsx"],
  theme: {
    extend: {
    },
  },
  plugins: [],
  presets: [nativewind],
};
```

**Comment by tehfailsafe** [comment] 2023-01-08 23:24
It's a super basic app with one page just to test this issue. I have been stuck on the `eas build` step on a real app I was working on and could not get it to finish. I isolated it down to this config file.

**Comment by marklawlor** [comment] 2023-01-08 23:32
I'm just coming back from break so I'll look into it soon. It could very well be the same issue, just getting stuck on a different output. It does seem like EAS/Metro has changed how they spawn children processes (as seen above with the different env).

**Comment by tehfailsafe** [comment] 2023-01-08 23:39
Anything I could try in the meantime? Trying to get a development build up on EAS for team reviews. Should I convert everything to `style={tailwind("class-names")}` ?  I like your approach with nativewind better, but I need to get something up for testing asap

**Comment by chrisarts** [comment] 2023-01-17 17:05
I tried every possible way to acheve the build in EAS but not possible right now, there is no node_modules involved or something like that, so I just downgrade, V3 is not ready yet.

**Comment by tyrauber** [comment] 2023-02-02 20:21
I am seeing the same issue with Nativewind v3 and Expo EAS. Unfortunately, @allpwrfulroot's suggestion did not work for me with `3.0.0-854ccd0.0`. I am using a monorepo very similar to [expo-monorepo-example](https://github.com/byCedric/expo-monorepo-exampl) with the following metro config:
```
// Learn more https://docs.expo.dev/guides/monorepos
const { getDefaultConfig } = require('expo/metro-config');
const { FileStore } = require('metro-cache');
const path = require('path');
const withNativewind = require("nativewind/metro");

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

// #1 - Watch all files in the monorepo
config.watchFolders = [workspaceRoot];
// #3 - Force resolving nested modules to the folders below
config.resolver.disableHierarchicalLookup = true;
// #2 - Try resolving with project modules first, then workspace modules
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];

// Remove all console logs in production...
// https://docs.expo.dev/guides/customizing-metro/
config.transformer.minifierConfig.compress.drop_console = true;

// Use turborepo to restore the cache when possible
config.cacheStores = [
  new FileStore({ root: path.join(projectRoot, 'node_modules', '.cache', 'metro') }),
];

module.exports = withNativewind(config);
```

I can replicate this issue locally using with the `--local` flag: 

```
eas build --platform ios --local
```
Removing withNativewind from the metro.config.js builds successfully.

**Comment by anurag-alla** [comment] 2023-02-06 12:15
I got it to work in eas build. As pointed by @chenhb23 this issue is with node env variable. I have used patch-package to fix this line. Below are the steps

1. Install patch-package and post-install ```yarn add patch-package postinstall-postinstall```
2. In package.json add this under scripts ``` "postinstall": "patch-package" ```
3. create patches folder in root of your app and paste attached file in the folder.

Now eas build works

[nativewind+3.0.0-next.34.patch](https://github.com/marklawlor/nativewind/files/10662852/nativewind%2B3.0.0-next.34.patch)

**Comment by tyrauber** [comment] 2023-02-06 15:20
Awesome, @anurag-alla, thanks for tracking this bug down.

Here [is the code in question](https://github.com/marklawlor/nativewind/blob/next/packages/nativewind/src/metro/tailwind.ts#L68).  

```
const isDevelopment = process.env.NODE_ENV !== "production";
```

The problem is EAS uses the `NODE_ENV` variable to determine the build environment (staging, beta, production, etc).  But nativewind@next is using `NODE_ENV` !== 'production' to enable fast-refresh.  Setting `isDevelopment` to false, enables non-production EAS building, but disables fast-refresh in development.  

It cannot be assumed that EAS will only be used for production, but fast-refresh in development would be helpful.

[A better solution](https://github.com/tyrauber/nativewind/commit/90fcc61cd1fc8dec0a92eaedbafd3475e9f351f2#diff-d5c799a45edb2382ae03145e8952e152cdc3dfcb7e4bfa2866c0a3125a126ec4R69-R70), I think, is to check the `process.env.CI` variable and disable fast-refresh if run in CI. (EXPO EAS also [sets the CI env variable for builds](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables)).

```
  const notCI = !(process.env.CI)
  if (isDevelopment && notCI) {
```

**Comment by anurag-alla** [comment] 2023-02-07 12:23
@tyrauber, sure will try your solution. But I see this issue with local builds too. For example, if I run ```./gradlew assembleRelease```, the build never finishes

**Comment by tyrauber** [comment] 2023-02-07 12:29
@anurag-alla, I was able to build (non-production) on EAS for iOS, but I am not seeing the styling on the build. Not sure if that is an issue with my implementation or with the above mentioned fix. Needs further investigation.

That's odd that `./gradlew assembleRelease`, I would imagine process.env.CI would be undefined.

**Comment by mauricedoepke** [comment] 2023-03-09 01:04
I have investigated this problem in more detail. 

It seems like expo/metro somehow explicitely wait till a spawned process is finished. And if nativewind starts tailwind in watchmode this never happens. I also tried to start it delayed by wrapping it with a setTimeout. But metro seems to also wait for all timeouts being finished till continueing.

Furthermore I discovered that the "getTransformOptions" method is sometimes called multiple times, so even if metro would not block, this method seems not to be ideal to hook into.

In General neither metro nor expo seem to have any kind of hook or middleware concept that would work for nativewinds purpose.

I guess it would be the easiest to keep the non watch mode inside the "getTransformOptions" and extract the watch mode into a cli, that one can put into a script inside the package.json to run alongside the expo cli.

**Comment by chrisarts** [comment] 2023-03-17 03:49
> I have investigated this problem in more detail.
> 
> It seems like expo/metro somehow explicitely wait till a spawned process is finished. And if nativewind starts tailwind in watchmode this never happens. I also tried to start it delayed by wrapping it with a setTimeout. But metro seems to also wait for all timeouts being finished till continueing.
> 
> Furthermore I discovered that the "getTransformOptions" method is sometimes called multiple times, so even if metro would not block, this method seems not to be ideal to hook into.
> 
> In General neither metro nor expo seem to have any kind of hook or middleware concept that would work for nativewinds purpose.
> 
> I guess it would be the easiest to keep the non watch mode inside the "getTransformOptions" and extract the watch mode into a cli, that one can put into a script inside the package.json to run alongside the expo cli.

That's right, but in that case I will fallback in a concurrent start command ?

**Comment by nareshbhatia** [comment] 2023-03-24 03:55
I think I am running into the same issue. I am using the following command line to build:

```shell
$ npx react-native run-ios --device
warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
info Found Xcode workspace "Driverless.xcworkspace"
info Using first available device named "Kunal’s iPhone" due to lack of name supplied.
info Building (using "xcodebuild -workspace Driverless.xcworkspace -configuration Debug -scheme Driverless -destination id=00008030-001245CA3A02802E")
⠦ Building the app......
```

The build gets stuck at the last line that says `Building the app......`.

Is there a workaround for this issue?

My `metro.config.js` looks like this:

```js
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const withNativewind = require('nativewind/metro');

module.exports = withNativewind({
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
});
```

Thanks in advance.

**Comment by AyoCodess** [comment] 2023-03-25 17:15
> I got it to work in eas build. As pointed by @chenhb23 this issue is with node env variable. I have used patch-package to fix this line. Below are the steps
> 
> 1. Install patch-package and post-install `yarn add patch-package postinstall-postinstall`
> 2. In package.json add this under scripts `"postinstall": "patch-package"`
> 3. create patches folder in root of your app and paste attached file in the folder.
> 
> Now eas build works
> 
> [nativewind+3.0.0-next.34.patch](https://github.com/marklawlor/nativewind/files/10662852/nativewind%2B3.0.0-next.34.patch)

This worked great, thank you! I hope this gets added to the library.

**Comment by nareshbhatia** [comment] 2023-03-25 22:49
I am using react-native CLI. Any workaround for that?

**Comment by anurag-alla** [comment] 2023-03-26 04:55
> I am using react-native CLI. Any workaround for that?

@nareshbhatia, Above solution works with react-native-cli too

**Comment by nareshbhatia** [comment] 2023-03-26 15:00
> @nareshbhatia, Above solution works with react-native-cli too

Got it. Will give it a try.

@marklawlor, any thoughts on a permanent fix?

**Comment by tomasmozeris** [comment] 2023-04-17 12:52
Is there way manually trigger rebuild on **new** className occurrence?

**Comment by andrewflo** [comment] 2023-05-18 09:19
> I got it to work in eas build. As pointed by @chenhb23 this issue is with node env variable. I have used patch-package to fix this line. Below are the steps
> 
> 1. Install patch-package and post-install `yarn add patch-package postinstall-postinstall`
> 2. In package.json add this under scripts `"postinstall": "patch-package"`
> 3. create patches folder in root of your app and paste attached file in the folder.
> 
> Now eas build works
> 
> [nativewind+3.0.0-next.34.patch](https://github.com/marklawlor/nativewind/files/10662852/nativewind%2B3.0.0-next.34.patch)

This fixed my issues. EAS Build was working fine with Nativewind v3 until I added `expo-updates` then the builds started timing out. Thanks for the help with this!

**Comment by smooth1884** [comment] 2023-09-02 02:19
Same issue after adding `expo-updates`, the fix above fixed the build but then the (Android) app was crashing on launch. removed `expo-updates` and it worked again as intended.  Guess i'll go without `expo-updates`.

**Comment by marklawlor** [comment] 2023-09-02 03:35
If adding a package to your `node_modules` is causing an issue, then it means your `content` glob includes your `node_modules`, which you shouldn't do as it can cause looping builds and generally slower builds (as it will scan every file)

**Comment by smooth1884** [comment] 2023-09-02 05:10
This problem only occurs when adding `expo-updates`. I have added a bunch of other packages all the time and it never was a problem. Also, my config should be correct like mentioned above: ` content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],`

**Comment by marklawlor** [comment] 2024-02-14 03:51
This has been fixed in v4, it also tries to detect if your have an invalid `content` path that will cause an infinite loop.

**Closed by marklawlor** 2024-02-14 03:51 UTC
