### ISSUE TITLE
Build Hangs in V4

### ISSUE THREAD

**Issue by revolution42** [marklawlor/nativewind#610] opened 2023-11-03 20:58 UTC
**Describe the bug**
I followed the expo-router instructions for v4.
When including the css file in _layout.css the build hangs

**To Reproduce**
1. Clone this repo https://github.com/revolution42/nativewind-demo
2. Run yarn start
3. Open in web mode (W)

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/322514/7a6407fd-6fc8-47cf-9bd4-435480ea4168)
Build will stay like this

**Comment by marklawlor** [comment] 2023-11-03 22:27
Sorry, little bit confusing because the docs are defaulting to Expo SDK 50 (which is not released yet). Can you try the SDK 49 instructions and modify your `metro.config.js`

```diff
- const config = getDefaultConfig(__dirname)
+ const config = getDefaultConfig(__dirname, { isCSSEnabled: true })
```

**Comment by revolution42** [comment] 2023-11-03 22:42
Seems like I am still getting the same issue

**Comment by marklawlor** [comment] 2023-11-03 22:45
When I clone your repo, I have issues with your dependencies. If I 

- remove the `package-lock.json` and `yarn.lock`
- change `metro` to `"metro": "~0.76.7",`
- update the `metro.config.js` as described above
- run `npm install`

The project loads fine with no issues. Can you try those steps

**Comment by revolution42** [comment] 2023-11-03 22:45
I upgraded the expo sdk to the alpha and it is doing the same thing.

Thank you for your time

**Comment by revolution42** [comment] 2023-11-03 23:29
I tried that (I updated the repo and same deal)

I did notice I was using an old version of node, I updated and still having
the same issue ( i cleared out my node modules)

Android builds however the web is still freezing

[image: image.png]

**Comment by marklawlor** [comment] 2023-11-04 00:00
Unfortunately I cannot replicate your issue. You removed your lockfile from the repo, so I cannot verify using the same dependencies as you. When you updated your `node_modules` did you also reset the Metro cache when rebuilding?

**Comment by revolution42** [comment] 2023-11-04 00:07
I am new to metro does this clear it "npx expo start -c" as i tried that.
I have put up my package.lock now

**Comment by marklawlor** [comment] 2023-11-04 00:40
Unfortunately I cannot replicate your issue, so you'll need to do some troubleshooting on your end to isolate the issue further.

For example, you should test if this is an Expo or NativeWind issue. You can remove `withNativeWind` from your `metro.config.js`. This will cause your styles not to load, but Expo should still insert the raw CSS file into the html. You should have an element like this in your `<body>`

```
<style data-expo-css-hmr="global_css" data-expo-loader="css">@tailwind base;
@tailwind components;
@tailwind utilities;

</style>
```

**Comment by revolution42** [comment] 2023-11-04 01:17
I changed it to

const { getDefaultConfig } = require("expo/metro-config");
> const { withNativeWind } = require('nativewind/metro');
> const config = getDefaultConfig(__dirname, { isCSSEnabled: true })
> module.exports = config;


It built however i didn't see the style tag that you mentioned

**Comment by marklawlor** [comment] 2023-11-04 01:41
NativeWind uses Expo's CSS file loading for the web. If your `.css` file is not appearing in the `.html` output then NativeWind will never work.

I would recommend creating a new project `npx create-expo-app@latest --template tabs@49` and verify that custom CSS loading is working. Once confirmed, then you should be able to setup NativeWind.

I'm going to close this issue because it appears to be an upstream issue. But if you get Expo Web working and still have problems with NativeWind & Metro, just reply and I can reopen

**Closed by marklawlor** 2023-11-04 01:41 UTC

**Comment by revolution42** [comment] 2023-11-04 05:29
I got it rendering the stylesheet

<style data-expo-css-hmr="global_css" ***@***.*** base;
@tailwind components;
@tailwind utilities;

.container {
    background-color: red;
  }</style>

as soon as I add in nativewind it freezes up

**Comment by marklawlor** [comment] 2023-11-04 06:23
Ok, I need more information and some more troubleshooting from you. 

Details about your system:
 - what system are you using
 - what command line are you using
 - do you have the same issue on a different computer

Details about the type of build
 - do production builds also free
 -if you using Expo Go, does it free when making a development build

I'm sure there is something fixable here, but we need to first discover the cause.

**Comment by revolution42** [comment] 2023-11-04 07:07
Details about your system:

   - what system are you using

Windows 11

   - what command line are you using

I am using powershell and yarn, i also tried clearing it all and using npm

   - do you have the same issue on a different computer

I spun up a azure windows computer and tried ubuntu in WSL and I got this
error message for both

> Error: Cannot find module '../lightningcss.linux-x64-gnu.node'
>
> Require stack:
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/react-native-css-interop/node_modules/lightningcss/node/index.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/react-native-css-interop/dist/css-to-rn/index.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/react-native-css-interop/css-to-rn/index.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/nativewind/dist/metro/tailwind-cli.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/nativewind/dist/metro/index.js
>
> - /home/shannon/Workspace/nativewind-demo/metro.config.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/import-fresh/index.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/cosmiconfig/dist/loaders.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/cosmiconfig/dist/createExplorer.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/cosmiconfig/dist/index.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/metro-config/src/loadConfig.js
>
> -
>> /home/shannon/Workspace/nativewind-demo/node_modules/metro-config/src/index.js
>
> -
>> ***@***.***/metro-config/build/traveling/metro-config.js
>
> -
>> ***@***.***/metro-config/build/ExpoMetroConfig.js
>
> -
>> ***@***.***/cli/build/src/start/server/metro/resolveFromProject.js
>
> -
>> ***@***.***/cli/build/src/utils/analytics/getMetroProperties.js
>
> -
>> ***@***.***/cli/build/src/start/server/metro/instantiateMetro.js
>
> -
>> ***@***.***/cli/build/src/start/server/metro/MetroBundlerDevServer.js
>
> -
>> ***@***.***/cli/build/src/start/server/DevServerManager.js
>
> -
>> ***@***.***/cli/build/src/start/startAsync.js
>
> -
>> ***@***.***/cli/build/src/start/index.js
>
> -
>> ***@***.***/cli/build/bin/cli
>
> - /home/shannon/Workspace/nativewind-demo/node_modules/expo/bin/cli
>
>

Details about the type of build

   - do production builds also free

Expo production mode freezes aswell
npx expo export -p web also freezes

   - if you using Expo Go, does it free when making a development build

Expo Go and Android with emulator work it looks like it is something to do
with the web build

**Comment by marklawlor** [comment] 2023-11-04 07:44
Ok  you will need to jump into the code to isolate the issue. The best method might be commenting out the Metro configuration to isolate what config is causing the issue. I'd do 1 step at a time, commenting out a section and then starting the app with the cache cleared to see if it was the cause

`node_modules/nativewind/dist/metro/index.js` contains the code that will need to be modified

1. Remove the transformer

```js
// line 34
metroConfig.transformerPath = require.resolve("./transformer");
```

2. Remove the transformerOptions

```js
   // line 40
    metroConfig.transformer = {
        ...metroConfig.transformer,
        nativewind: {
            input,
            output,
        },
        getTransformOptions: async (entryPoints, options, getDependenciesOf) => {
            if (!output || !input)
                throw new Error("Invalid NativeWind config");
            if (process.stdout.isTTY) {
                process.stdout.clearLine(0);
                process.stdout.cursorTo(0);
            }
            const platform = options.platform === "web" ? "web" : "native";
            if (!tailwindHasStarted[platform]) {
                tailwindHasStarted[platform] = true;
                const cliOutput = await (0, tailwind_cli_1.tailwindCli)(input, metroConfig, {
                    ...options,
                    output,
                    cliCommand,
                    hotServerOptions,
                });
                if (cliOutput) {
                    Object.assign(metroConfig.transformer.nativewind, cliOutput);
                }
            }
            return previousTransformOptions?.(entryPoints, options, getDependenciesOf);
        },
    };
```

3. Remove the CSS interop

```js
// line 29
metroConfig = (0, metro_1.withCssInterop)(metroConfig, {
    ...common_1.cssToReactNativeRuntimeOptions,
    inlineRem,
    selectorPrefix: typeof importantConfig === "string" ? importantConfig : undefined
});
```

Those are the 3 things the NativeWind changes in your Metro config.

**Comment by revolution42** [comment] 2023-11-04 08:47
When I remove the line at 34 it compiles and doesn't freeze however the
style is not converted

**Comment by marklawlor** [comment] 2023-11-04 09:54
Line 34 controls the code transformation.

You will need debug in  `node_modules/nativewind/dist/metro/transformer.js`. Can you comment out lines 11-21

```diff
async function transform(config, projectRoot, filename, data, options) {
-    if (path_1.default.resolve(process.cwd(), filename) === config.nativewind.input) {
-        if (options.platform !== "web" && options.dev && options.hot) {
-            return metro_transform_worker_1.default.transform(config, projectRoot, filename, Buffer.from(`const { StyleSheet } = require("react-native-css-interop");
-const url = require("react-native/Libraries/Core/Devtools/getDevServer")().url.replace(/(https?:\\/\\/.*)(:\\d*\\/)(.*)/, "$1$3")
- new globalThis.WebSocket(\`\${url}:${config.nativewind.fastRefreshPort}\`).addEventListener("message", (event) => StyleSheet.register(JSON.parse(event.data)));
- StyleSheet.register(JSON.parse('${config.nativewind.initialData}'));`, "utf8"), options);
-        }
-        else {
-            return metro_transform_worker_1.default.transform(config, projectRoot, filename, Buffer.from(`import '${config.nativewind.output}'`, "utf8"), options);
-       }
-   }
       return (0, transformer_1.transform)(config, projectRoot, filename, data, options);
}
```

**Comment by revolution42** [comment] 2023-11-04 10:27
I got it down to just commenting out line 19

These are the values of the variables

 {
>
>    config: {
>
>      assetPlugins: [
>
>
>>  'C:\\Workspace\\abcoui\\node_modules\\expo-asset\\tools\\hashAssetFiles.js'
>
>      ],
>
>      asyncRequireModulePath: 'metro-runtime/src/modules/asyncRequire',
>
>      assetRegistryPath: 'react-native/Libraries/Image/AssetRegistry',
>
>      babelTransformerPath:
>> 'C:\\Workspace\\abcoui\\node_modules\\metro-react-native-babel-transformer\\src\\index.js',
>
>      dynamicDepsInPackages: 'throwAtRuntime',
>
>      enableBabelRCLookup: true,
>
>      enableBabelRuntime: true,
>
>      globalPrefix: '',
>
>      hermesParser: false,
>
>      minifierConfig: {
>
>        mangle: [Object],
>
>        output: [Object],
>
>        sourceMap: [Object],
>
>        toplevel: false,
>
>        compress: [Object]
>
>      },
>
>      minifierPath: 'metro-minify-terser',
>
>      optimizationSizeLimit: 153600,
>
>      publicPath: '/assets',
>
>      allowOptionalDependencies: true,
>
>      unstable_allowRequireContext: true,
>
>      unstable_dependencyMapReservedName: null,
>
>      unstable_disableModuleWrapping: false,
>
>      unstable_disableNormalizePseudoGlobals: false,
>
>      unstable_compactOutput: false,
>
>      postcssHash: null,
>
>      browserslistHash: null,
>
>      sassVersion: null,
>
>      cssToReactNativeRuntime: {
>
>        ignorePropertyWarningRegex: [Array],
>
>        grouping: [Array],
>
>        inlineRem: 14
>
>      },
>
>      transformerPath:
>> ***@***.***\\metro-config\\build\\transform-worker\\transform-worker.js',
>
>      nativewind: {
>
>        input: 'C:\\Workspace\\abcoui\\global.css',
>
>        output:
>> 'C:\\Workspace\\abcoui\\node_modules\\.cache\\nativewind\\global.css'
>
>      },
>
>      _expoRouterRootDirectory: '..\\..\\app',
>
>      _expoRouterWebRendering: 'single'
>
>    },
>
>    projectRoot: 'C:\\Workspace\\abcoui',
>
>    filename: 'global.css',
>
>    data: <Buffer 40 74 61 69 6c 77 69 6e 64 20 62 61 73 65 3b 0d 0a 40 74
>> 61 69 6c 77 69 6e 64 20 63 6f 6d 70 6f 6e 65 6e 74 73 3b 0d 0a 40 74 61 69
>> 6c 77 69 6e 64 20 ... 57 more bytes>,
>
>    options: {
>
>      customTransformOptions: {},
>
>      dev: true,
>
>      hot: true,
>
>      inlinePlatform: true,
>
>      minify: false,
>
>      platform: 'web',
>
>      unstable_transformProfile: 'default',
>
>      experimentalImportSupport: false,
>
>      unstable_disableES6Transforms: false,
>
>      nonInlinedRequires: [ 'React', 'react', 'react-native' ],
>
>      type: 'module',
>
>      inlineRequires: false
>
>    }
>
>  }
>
>

**Comment by revolution42** [comment] 2023-11-04 11:38
Trying to debug a little myself

I am not sure if the means anything

C:\\Workspace\\abcoui\\node_modules\\.cache\\nativewind\\global.css does
not exists
however in the same directory is global.css.web.css which looks like it has
compiled tailwind

**Comment by marklawlor** [comment] 2023-11-04 12:33
The logic is:

 - Tailwind CLI should create `node_modules/. cache/NativeWind/global.css.web.css`
- NativeWind has a transformer that when `global.css` is loaded, it rewrites it to a Javascript file importing the generated `.css` file
- When the generated CSS file is read, it should be processed by the previous transformer (the Expo one, which extracts it to a style tag in your html)

So if a path is wrong, the process breaks. This might be a Windows pathing issue, but I don't have access to a Windows computer until Monday to debug.

Altho I haven't seen anything also far that would cause this to hang. Normally Metro would error that the file was not found.

**Comment by marklawlor** [comment] 2023-11-06 07:25
Can you try `4.0.9`,  the transformer was rewritten to resolve another issue but it may solve your issue as well.

**Comment by revolution42** [comment] 2023-11-06 10:51
It looks like it is a windows path issue.

[image: image.png]

I will try and debug a little more later tonight if I get a chance

**Comment by revolution42** [comment] 2023-11-06 11:37
This is not the actual fix however this makes it work.

\node_modules\nativewind\dist\metro\index.js

adding in line 37

getTransformOptions: async (entryPoints, options, getDependenciesOf) => {
>
> input = 'global.css'; // add in this line
>
>             const output = path_1.default.resolve(projectRoot,
>> path_1.default.join(outputDir, input));
>
>

**Comment by revolution42** [comment] 2023-11-06 12:48
I am using 4.0.9

This is not the actual fix however this makes it work.

\node_modules\nativewind\dist\metro\index.js

adding in line 37

getTransformOptions: async (entryPoints, options, getDependenciesOf) => {
			input = 'global.css'; // add in this line
            const output = path_1.default.resolve(projectRoot, path_1.default.join(outputDir, input));

**Comment by marklawlor** [comment] 2023-11-10 01:00
I've fixed a number of Window's related issues in the last couple of releases so you may want to try again. All of the reported issues had error messages, so they may not be the same issue your seeing. But with any luck it may fix the problem

**Comment by LiniovasDovydas** [comment] 2023-12-18 11:28
Adding my two cents:
Had the same issue that native apps were compiling but the web hanged for some reason:

1. Changed the output dir to be the same as input for
```
module.exports = withNativeWind(config, {
  input: './src/lib/tailwind/globals.css',
  outputDir: './src/lib/tailwind',
});
```
2. Created entry files based on the platform `index.web.tsx` and `index.native.tsx` in  `./src/components/entry` 
3. Imported css based on the platform in those files `import `../../lib/tailwind/global.css.native.css` and `../../lib/tailwind/global.css.web.css`
4. Imported the entry in expo router `app/_layout.tsx`

 Both are working fine with fast refresh

**Comment by sxxov** [comment] 2024-01-14 22:14
Having this issue as well. I found that this branch would cause the hang:

https://github.com/marklawlor/nativewind/blob/32b937111a1820ac5f7e4e422bb12a31122e9564/packages/nativewind/src/metro/transformer.ts#L47

Commenting it out & letting it fall back to the last `else` case would make it compile fine for the web, but lose the ability to include new classes on hot-reload. Mayhap there's a deeper error somewhere in `metro-transform-worker` but it's being swallowed by the worker?

If it helps, I'm also on Windows, using Expo SDK 50 (`50.0.0-preview.10`), `nativewind@4.0.22`, & I can add a repro if needed.

## Workaround

```diff
- import '../../global.css';
+ import '../../node_modules/.cache/nativewind/global.css';
```

**Comment by sxxov** [comment] 2024-01-15 11:14
Haha it was a windows path issue!

```diff
    } else if (options.platform === "web") {
      return worker.transform(
        config,
        projectRoot,
        filename,
-        Buffer.from(`require('${config.nativewind.outputPath}');`, "utf8"),
+        Buffer.from(`require('${config.nativewind.outputPath.replace(/\\/g, '\\\\')}');`, "utf8"),
        options,
      );
    } else {
```

The backslashes in windows paths would become unescaped escape sequences; escaping them again fixes the issue.

**Comment by neverson-silva** [comment] 2024-01-22 04:14
I'm having this issue either

**Comment by JorrinKievit** [comment] 2024-01-27 15:42
Also having this issue

**Comment by Olgsie** [comment] 2024-03-13 12:19
Hi, this fix seems to have been undone again in this commit https://github.com/marklawlor/nativewind/commit/72ff611cc4fb08ca9e6265d6e1496e4b64a7de78#diff-3b3d28940d6e4a5ad11860e5a017afef5641e4f9becc71e403a638a77ed76539R24 

Could you please restore it? Running into this issue now 🙏

**Comment by Steven-zion** [comment] 2024-03-31 23:59
solution by @sxxov worked , thanks buddy i've been stuck on this problem for a while now

**Comment by rodnoycry** [comment] 2024-04-18 23:23
Please reopen, same issue after commit that was mentioned by Olgsie

**Comment by Steven-zion** [comment] 2024-04-19 21:55
@rodnoycry this was already solved check answer at the top, one with most reactions

**Comment by rodnoycry** [comment] 2024-04-22 05:08
@Steven-zion fix was overwritten in commit [72ff611#diff-3b3d28940d6e4a5ad11860e5a017afef5641e4f9becc71e403a638a77ed76539R24](https://github.com/marklawlor/nativewind/commit/72ff611cc4fb08ca9e6265d6e1496e4b64a7de78#diff-3b3d28940d6e4a5ad11860e5a017afef5641e4f9becc71e403a638a77ed76539R24) as was earlier mentioned by Olgsie, you can check it out, also versions of nativewind after 4.0.25 doesn't include this fix.

**Comment by DanG-Mergin** [comment] 2024-05-08 03:02
> Please reopen, same issue after commit that was mentioned by Olgsie If anyone encountered same issue, installing v4.0.25 helped me:
> 
> ```shell
> npm i nativewind@4.0.25
> ```

Finally after days of struggle...  at least it loads web (expo 50.0.14, expo-router 3.4.1, react-native-web 0.19.6)

**Comment by vedantb2** [comment] 2024-08-08 18:24
> Having this issue as well (pls reopen 🥸). I found that this branch would cause the hang:
> 
> https://github.com/marklawlor/nativewind/blob/32b937111a1820ac5f7e4e422bb12a31122e9564/packages/nativewind/src/metro/transformer.ts#L47
> 
> Commenting it out & letting it fall back to the last `else` case would make it compile fine for the web, but lose the ability to include new classes on hot-reload. Mayhap there's a deeper error somewhere in `metro-transform-worker` but it's being swallowed by the worker?
> 
> If it helps, I'm also on Windows, using Expo SDK 50 (`50.0.0-preview.10`), `nativewind@4.0.22`, & I can add a repro if needed.
> 
> ## Workaround
> ```diff
> - import '../../global.css';
> + import '../../node_modules/.cache/nativewind/global.css';
> ```

wow this fix still works :)

**Comment by ohyajk** [comment] 2024-08-09 04:03
> > Having this issue as well (pls reopen 🥸). I found that this branch would cause the hang:
> > https://github.com/marklawlor/nativewind/blob/32b937111a1820ac5f7e4e422bb12a31122e9564/packages/nativewind/src/metro/transformer.ts#L47
> > Commenting it out & letting it fall back to the last `else` case would make it compile fine for the web, but lose the ability to include new classes on hot-reload. Mayhap there's a deeper error somewhere in `metro-transform-worker` but it's being swallowed by the worker?
> > If it helps, I'm also on Windows, using Expo SDK 50 (`50.0.0-preview.10`), `nativewind@4.0.22`, & I can add a repro if needed.
> > ## Workaround
> > ```diff
> > - import '../../global.css';
> > + import '../../node_modules/.cache/nativewind/global.css';
> > ```
> 
> wow this fix still works :)

Not working

**Comment by DanyBv98** [comment] 2024-08-09 23:57
> > > Having this issue as well (pls reopen 🥸). I found that this branch would cause the hang:
> > > https://github.com/marklawlor/nativewind/blob/32b937111a1820ac5f7e4e422bb12a31122e9564/packages/nativewind/src/metro/transformer.ts#L47
> > > Commenting it out & letting it fall back to the last `else` case would make it compile fine for the web, but lose the ability to include new classes on hot-reload. Mayhap there's a deeper error somewhere in `metro-transform-worker` but it's being swallowed by the worker?
> > > If it helps, I'm also on Windows, using Expo SDK 50 (`50.0.0-preview.10`), `nativewind@4.0.22`, & I can add a repro if needed.
> > > ## Workaround
> > > ```diff
> > > - import '../../global.css';
> > > + import '../../node_modules/.cache/nativewind/global.css';
> > > ```
> > 
> > 
> > wow this fix still works :)
> 
> Not working

Try 
`import '../node_modules/.cache/nativewind/global.css.native.css';`

This worked for me.

**Comment by bkomadina** [comment] 2025-01-26 18:28
Had the same problem on version `4.1.23`. I've updated tailwind.config.js to include all folders where components exist: `content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"]`
and ran: `npx expo start -c` which clears cache and it built succesfully afterwards

**Comment by Tejasp2003** [comment] 2025-02-02 09:39
Getting same issue!! Expo go struck at 98%,

**Comment by faizhussain7** [comment] 2025-02-18 18:21
stuck at 98% did you solved @Tejasp2003 
this happening if importing global CSS, if not working fine

```
"dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/native": "^7.0.3",
    "expo": "^52.0.35",
    "expo-constants": "~17.0.6",
    "expo-document-picker": "~13.0.3",
    "expo-linking": "~7.0.5",
    "expo-router": "~4.0.6",
    "expo-status-bar": "~2.0.1",
    "expo-system-ui": "~4.0.8",
    "expo-web-browser": "~14.0.2",
    "nativewind": "^4.1.23",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.7",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "3.16.2",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-web": "~0.19.10",
    "react-native-webview": "13.12.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.3.12",
    "@typescript-eslint/eslint-plugin": "^7.7.0",
    "@typescript-eslint/parser": "^7.7.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^8.57.0",
    "eslint-config-universe": "^12.0.1",
    "postcss": "^8.5.2",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.11",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
```

**Comment by mrakus-sofomo** [comment] 2025-04-01 15:32
Im experiencing it on 4.1.23

**Comment by YowaiCoder** [comment] 2025-04-21 07:19
I've seen many closed issues addressing this same problem :(

**Comment by sb55555** [comment] 2025-04-28 16:26
You may have a syntax error in your `global.css` and the build will get stuck silently. 

Run the following command to check.
`npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css`

After fixing the syntax error in my global.css the build finished and it worked for me.  
May it work for you
