### ISSUE TITLE
v4: "Release" configuration building directly through Xcode hangs when native wind installed

### ISSUE THREAD

**Issue by ae99** [marklawlor/nativewind#641] opened 2023-11-13 01:38 UTC
**Describe the bug**
With Nativewind v4, I am unable to build with release configuration directly through Xcode.

**To Reproduce**
1. Setup barebones expo + RN project
2. Configure nativewind per v4 instructions in docs.
3. Open workspace in Xcode, set Scheme's build configuration to Release
4. Run project - observe that build hangs

**Expected behavior**
Expect project to build successfully.

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**
Running `expo run:ios` and `expo run:ios --configuration Release` each work as expected, or building in Xcode with Debug build configuration works as expected.

Removing `withNativeWind` in `metro.config.js` allows build to succeed again.
```
- module.exports = withNativeWind(config, { input: './global.css' })
+ module.exports = config
```

Frustratingly I haven't quite figured out how to reproduce this other than inside Xcode itself - so haven't been able to find any logs pointing to why or where the build hangs.

**Comment by marklawlor** [comment] 2023-11-14 04:07
I've had reports of this occurring, but I am unable to reproduce the issue. I'm assuming this is an environmental issue which hasn't been identified yet. I would really appreciate any help in debugging the issue.

`withNativeWind()` may hold up the build process if starting Tailwind CLI fails

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/index.ts#L108

I would first test that promise is resolving/rejecting and contains data.

If Tailwind CLI runs correct, we take the output and "swap" the contents of your `.css` file with the output from Tailwind CLI 

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/transformer.ts#L45C6-L45C6

That code is then turned into JavaScript

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/react-native-css-interop/src/metro/transformer.ts#L27-L45

**Comment by ae99** [comment] 2023-11-14 05:41
Hey! Just confirmed, looks like it's the CLI not starting, `await` never resolves.

**Comment by marklawlor** [comment] 2023-11-14 05:53
Ok cool, narrows down the problem a lot.

All the related code is in https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/tailwind-cli.ts

It creates a deferred that only resolves when Tailwind CLI has completed

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/tailwind-cli.ts#L27-L32

This is where we spawn a subprocess start Tailwind CLI

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/tailwind-cli.ts#L91-L97

Tailwind CLI is writing to your file system, so we wait until we see the output "Done In"

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/tailwind-cli.ts#L100-L121

Then we resolve the deferred

https://github.com/marklawlor/nativewind/blob/1d1518b0afa79b4bdb738ce69462e80e05c6fda0/packages/nativewind/src/metro/tailwind-cli.ts#L147

So...if the deferred isn't resolving or rejecting maybe that Tailwind CLI is simply failing to spawn.

**Comment by ae99** [comment] 2023-11-14 06:06
Ahh... did some logging there - process gives back...
```
/bin/sh: npx: command not found
```

**Comment by marklawlor** [comment] 2023-11-14 06:15
Can you describe how you got that error? As I'll need to catch it and call `reject()` so the build doesn't stall

**Comment by ae99** [comment] 2023-11-14 06:17
Writing output of
```
 cli.stderr.on("data", (data: Buffer | string) => { 
   data = data.toString(); 
```
to a log file

So just adding a 
```
if (data.includes('command not found')
```
would catch it

**Comment by ae99** [comment] 2023-11-14 06:34
To follow up if others hit this - Xcode just seems to not know where to find `npx` and `node` for some reason. Running
```
sudo ln -s $(which npx) /usr/local/bin/npx
sudo ln -s $(which node) /usr/local/bin/node
```
And issue is solved!

**Closed** 2023-11-18 22:36 UTC
