### ISSUE TITLE
v4: remapProps use of Map is not working in some cases

### ISSUE THREAD

**Issue by johnf** [marklawlor/nativewind#597] opened 2023-10-31 00:02 UTC
**Describe the bug**
I see some strange behaviour around `remapProps` where not all styles are applied. In my example the font size works but the color doesn't.

**Additional context**

I think the problem lies in the use of WeakMap when calculating the styles
* https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/css-interop.native.ts#L122-L127
* https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/native/misc.ts#L13-L17

Maybe it gets garbage collected too early?

**Expected behavior**
Styles are correctly applied

**To Reproduce**
My actual code is this
```jsx
import DropDownPicker from 'react-native-dropdown-picker';                                                                                                                                                     

remapProps(DropDownPicker, {
  className: 'style',
  containerClass: 'containerStyle',
  disabledClass: 'disabledStyle',
  textClass: 'textStyle',
  labelClass: 'labelStyle',
  placeholderClass: 'placeholderStyle',
});

export const App = () => {
// Snip dropdown picker setup
  return (
    <DropDownPicker
      placeholder="Set your currency"
      placeholderClass="text-3xl text-red-0"
      // snip irrelevant props
    />
  );
};
```
But I've created a reproduction without nativewind entirely using weakmap

```jsx
import React from 'react';
import {
  Text,
  TextProps,
  View,
} from 'react-native';

const opaqueStyles = new WeakMap();
const styleMetaMap = new WeakMap();

const App = () => {
  // const styles = [{ color: 'red' }, { fontSize: 30 }];
  const styles = [{ fontSize: 30 }, { color: 'red' }];

  const rawStyles: TextProps['style'] = [];
  styles.forEach((style) => {
    const opaqueStyle = {};
    opaqueStyles.set(opaqueStyle, style);
    styleMetaMap.set(opaqueStyle, {});
    rawStyles.push(opaqueStyle);
  });

  console.debug('styles', styles);
  console.debug('rawStyles', rawStyles);

  return (
    <View>
      <Text style={styles}>Nrmal Styles</Text>
      <Text style={rawStyles}>Weak Map</Text>
    </View>
  );
}
```

I tried using a map but that doesn't seem to make any difference so maybe RN just doesn't like maps?

FYI: The maps do weird things in dev tools since the console.log to {} instead of the contents.

**Comment by johnf** [comment] 2023-10-31 00:14
Actually I just looked at the code again and I think that I over complicated I think the code is just wrong
```jsx
const opaqueStyle = {};
opaqueStyles.set(opaqueStyle, style);
styleMetaMap.set(opaqueStyle, {});
rawStyles.push(opaqueStyle);
```

Should the last line just be pushing style?

**Comment by marklawlor** [comment] 2023-10-31 01:16
`style` may not be a "style" object as React Native developers know it and because these objects can be accessed in people's components it may cause their code to break

To prevent breaking people's code, remapProps uses a placeholder empty style (this is why its called `opaqueStyle`) which is swapped back with the proper style later on.

**Comment by marklawlor** [comment] 2023-10-31 03:13
This is a duplicate of #596. Your styles are being calculated correctly but are being applied in the wrong order (its picking the default `#000` over your text color.

**Closed by marklawlor** 2023-10-31 03:13 UTC

**Comment by johnf** [comment] 2023-10-31 03:38
@marklawlor Ahh OK sorry for wasting time on this one, I should have remembered that bug as it was only yesterday I filed it!
