### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by Yankzy** [marklawlor/nativewind#436] opened 2023-03-11 06:43 UTC
Hi everyone,
My first time trying nativewind and am getting this error:

ERROR  TypeError: Cannot read property 'create' of undefined, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

I get the error if write `className="css here"`
if I remove it, I get no error.

MY CONFIGS:
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}", 
    "./<custom directory>/**/*.{js,jsx,ts,tsx}"
],
  theme: {
    extend: {},
  },
  plugins: [],
}

module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ["nativewind/babel"],
  };
};

Am using expo

**Comment by marklawlor** [comment] 2023-03-11 23:54
Duplicate of https://github.com/marklawlor/nativewind/issues/426 https://github.com/marklawlor/nativewind/issues/286. Please use search before opening an issue.

**Closed by marklawlor** 2023-03-11 23:54 UTC
