### ISSUE TITLE
Fast Refresh Not working with monorepo

### ISSUE THREAD

**Issue by Jm-Zion** [marklawlor/nativewind#804] opened 2024-02-18 23:02 UTC
Hello there, 

First of all, thanks for this amazing project.

I followed the documentation to configure the app in a monorepo using yarn workspaces. 

When I'm updating classnames from the inside apps/expo-app/App.tsx, FastRefresh is working well. 
When I'm updating classnames from the inside package apps/package1/src/myfile.ts, FastRefresh is not working ( styles are not updated ) , I've to press R.

**To Reproduce**
Create package 1 with following config  : 

```
/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "../../packages/ui-kit/**/*.{js,ts,tsx,ts}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "rgb(99 102 241)",
        secondary: "rgb(251 191 36)",
      },
    },
  },
  plugins: [],
};
```

App configuration ( metro ) : 

```

const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require("nativewind/metro");
const path = require("path");

// Find the project and workspace directories
const projectRoot = __dirname;

// This can be replaced with `find-yarn-workspace-root`
const monorepoRoot = path.resolve(projectRoot, "../../");

const monorepoPackages = {
  "@app/ui-kit": path.resolve(monorepoRoot, "packages/ui-kit"),
};

const config = getDefaultConfig(projectRoot, {
  isCSSEnabled: true,
});

config.resolver.disableHierarchicalLookup = true;

// 1. Watch all files within the monorepo
config.watchFolders = [projectRoot, ...Object.values(monorepoPackages)];

// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(monorepoRoot, "node_modules"),
];

module.exports = withNativeWind(config, {
  input: "./global.css",
});
```

babel : 
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: ["react-native-reanimated/plugin"],
  };
};

```

App tailwind config : 

```
const config = require("../../packages/ui-kit/tailwind.config");
module.exports = config;
```

**Expected behavior**

Styles should updates even when updated from packages.

**Comment by marklawlor** [comment] 2024-02-18 23:17
Please follow the troubeshooting guide for both [NativeWind](https://www.nativewind.dev/v4/guides/troubleshooting) and [TailwindCSS](https://tailwindcss.com/docs/content-configuration#troubleshooting).

Unfortunately I'm going to close this issue because you have no provided a full reproduction. To give you an answer, I'm going to need to run the code to see what the problem is. Code snippets are not useful, as the issue maybe with a file you did not share.

**Closed by marklawlor** 2024-02-18 23:17 UTC
