### ISSUE TITLE
Integrating with Solito

### ISSUE THREAD

**Issue by enesozturk** [marklawlor/nativewind#164] opened 2022-08-11 18:42 UTC
**Describe the bug**
I'm trying to create an example repo with Solito and Nativewind. I previously did set up Nativewind with the Expo app and it's working well. Today when I try to make it work with Solito I got the following error. It might be a dependency issue but couldn't figure it out. Any idea how to solve it?

**To Reproduce**
Reproducible example repo: https://github.com/enesozturk/solito-nativewind
You can find the [babel config](https://github.com/enesozturk/solito-nativewind/blob/main/apps/expo/babel.config.js) and [Tailwind config](https://github.com/enesozturk/solito-nativewind/blob/main/apps/expo/tailwind.config.ts) here.

1. Fork the repo
2. Install dependencies with `yarn`
3. Run `yarn native`

**Expected behavior**
Style the components with Nativewind.

**Screenshots**
<details>
<summary> See Image </summary>

<img width="483" alt="Screen Shot 2022-08-11 at 21 43 26" src="https://user-images.githubusercontent.com/19428358/184215557-3811c9f1-6731-45dc-8325-1e9e0c1947fc.png">

</details>

Also, @nandorojo might have an idea for this. I would appreciate any help 🙌🏽

**Comment by enesozturk** [comment] 2022-08-11 21:06
On the Next.js app, I'm getting the following error. It's a high-possibly dependency resolving issue due to structure of Solito. Trying to solve it rn.

```sh
Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/enesozturk/my-app-path/my-project/node_modules/react-native/index.js (14)
...
...
```

**Comment by enesozturk** [comment] 2022-08-11 21:11
Adding `nativewind`to the `next-transpile-modules` solve the issue on the Next app 👍🏽

**Comment by enesozturk** [comment] 2022-08-17 06:53
Any update on this? Did you guys able to checkout? @nandorojo @marklawlor

**Comment by marklawlor** [comment] 2022-08-17 21:38
I was unable to reproduce it, but I'm travelling and didn't completely troubleshoot the issue. 

I suspect it's your cache with can be resolved by following the troubleshooting guide https://www.nativewind.dev/guides/troubleshooting

**Comment by enesozturk** [comment] 2022-08-18 21:36
Hi @marklawlor, thank you so much to check out the issue in your limited time. I also suspected cache and dependencies and tried clearing cache, trying to repo on new Solito app (I was able to repro), and adding dependencies at different levels of the app. Still same. 

Now I tried the implementation steps in the troubleshooting guide. It's still the same for me. I'll continue checking.

**Comment by marklawlor** [comment] 2022-08-21 04:05
There are a couple of issues with your code:

### You have misnamed your config file

You have `tailwind.config.ts` instead of `tailwind.config.js`. NativeWind has a bug here when it should fail if it cannot find a suitable config file. Without the config file, NativeWind is getting confused and not failing gracefully

### You have your Expo app set to compile only. 

The compile-only mode is a performance boost when you choose not to use `className` and instead write all your components via `styled()`. Because you are using `className`, you should simply remove the mode setting and use the default.

### Tailwind content can be improved

This one is on me, but the content regex can be improved. Currently its scanning the `node_modules` of the `app` folder. A better version is

```
content: ['./App.{js,jsx,ts,tsx}', '../../packages/app/{features,navigation,provider}/**/*.{js,jsx,ts,tsx}']
```

**Closed by marklawlor** 2022-08-21 04:05 UTC

**Comment by enesozturk** [comment] 2022-08-24 09:00
I can confirm that the issue was resolved by changing the Tailwind config file extension to `.js`.  Thanks, @marklawlor!

**Comment by dohomi** [comment] 2022-08-25 03:17
@marklawlor I am doing the same approach as @enesozturk but trying to get NextJS running with the monorepo setup of Solito. I followed the NextJS 
```
error - SyntaxError: Cannot use import statement outside a module
```
@enesozturk did you get the NextJS app up and running?

**Comment by marklawlor** [comment] 2022-08-25 03:24
Anytime you get that error when running React Native in Next.js it means you need to add the module to your transpile list. This is typically done via `next-transpile-modules`

I'll update the docs adding a note of this, but this is actually part of the React Native Web documentation and something you should be aware of when running React Native on web.

**Comment by dohomi** [comment] 2022-08-25 03:26
@marklawlor you mean `nativewind` needs to be added to the next-transpile-modules? https://github.com/enesozturk/solito-nativewind/blob/3736af9cc9291dc8a45748583d7ced617da8762b/apps/next/next.config.js#L11

**Comment by marklawlor** [comment] 2022-08-25 03:28
If you are getting that error yes. Sometimes it is not needed and I'm not 100% sure why

**Comment by dohomi** [comment] 2022-08-25 03:30
@marklawlor yes after adding `nativewind` to the list it woks, thanks a lot!! 

Off topic, but did you ever tried (by any chance) to enable [`DaisyUI`](https://github.com/saadeghi/daisyui) styles to nativewind?

**Comment by marklawlor** [comment] 2022-08-25 03:39
I have not tried, but I suspect it should mostly work. 

If you have issue issues it will be because of unsupported classNames/pseudo classes/units.

If you have any layout bugs it's probably because React Native's has different Flex model defaults, which could be fixed via PRing to DaisyUI and making their classes more explicit

**Comment by dohomi** [comment] 2022-08-25 03:41
Ok thanks for the info I will give it a try
