### ISSUE TITLE
Reopening App causes flickering.

### ISSUE THREAD

**Issue by SalihColak** [marklawlor/nativewind#747] opened 2024-01-17 15:07 UTC
The app first shows the styles for dark / light mode then the right version of styles everytime when I close and reopen the app (from the background or initial boot)

![Neues Projekt 1](https://github.com/marklawlor/nativewind/assets/49074099/2cbcb340-e42f-4bb0-a43a-e4ba33510c41)

(Demo is at 50% speed)

**Comment by marklawlor** [comment] 2024-02-14 01:40
Duplicate of #478

**Closed by marklawlor** 2024-02-14 01:40 UTC
