### ISSUE TITLE
Latest version of tailwindcss 3.4.0

### ISSUE THREAD

**Issue by BilalDev** [marklawlor/nativewind#718] opened 2023-12-28 13:11 UTC
**Describe the bug**
When I run the commands mentioned in the documentation for React Native CLI, I got this error below:

`error: App.tsx: ..../App.tsx: Use process(css).then(cb) to work with async plugins`

**To Reproduce**
1. npx react-native init AwesomeProject
2. cd AwesomeProject
3. yarn add nativewind
4. yarn add --dev tailwindcss
5. npx tailwindcss init
6. add `content: ["./App.{js,jsx,ts,tsx}", "./<custom-folder>/**/*.{js,jsx,ts,tsx}"],` in tailwind.config.js
7. add `plugins: ["nativewind/babel"],` in babel.config.js
8. update App.tsx with basic `className` with tailwindcss classes

This is my tailwindcss version:
`"tailwindcss": "3.4.0",`

It works fine when I downgrade to version `3.3.2` with `"react-native": "0.73.1"`

**Comment by emmanuelchucks** [comment] 2023-12-29 01:43
Duplicate of #498

**Closed** 2024-01-03 05:18 UTC

**Comment by Kuldeepsinghrajpoot** [comment] 2024-02-13 10:13
not working right now
