### ISSUE TITLE
using with react-icomoon

### ISSUE THREAD

**Issue by iamhaaamed** [marklawlor/nativewind#354] opened 2022-12-01 07:31 UTC
Is it possible to use nativewind with react-icomoon?
I have used it like this:
```
import { styled } from 'nativewind';
import * as React from 'react';
import type { IconProps } from 'react-icomoon';
import IcoMoon from 'react-icomoon';
import { Path, Svg } from 'react-native-svg';

import iconSet from './selection.json';

const SIcoMoon = styled(IcoMoon);
export type NTIconProps = IconProps & {
  className?: string;
};

export const Icon = ({ className, style, ...props }: NTIconProps) => {
  return (
    <SIcoMoon
      native
      SvgComponent={Svg}
      PathComponent={Path}
      iconSet={iconSet}
      size={20}
      style={style}
      className={className}
      {...props}
    />
  );
};
```
but it's not working.

**Comment by marklawlor** [comment] 2022-12-01 07:56
Can you please describe your issue more, and your setup. Do other components work, is it just this one that is failing? Do normal inline-styles work?

If you are using the Babel plugin, the className is not passed down - it is turned into a object and passed via `style` https://www.nativewind.dev/guides/custom-components.

**Comment by iamhaaamed** [comment] 2022-12-01 08:12
Neither class nor style works for react-icomoon. I have used it for example with react native components and also other components like fast image and it's working but not with react-icomoon. 
This is my babel config:
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          root: ['./'],
          alias: {
            '@': './src',
            '@config': './config',
          },
          extensions: [
            '.ios.ts',
            '.android.ts',
            '.ts',
            '.ios.tsx',
            '.android.tsx',
            '.tsx',
            '.jsx',
            '.js',
            '.json',
          ],
        },
      ],
      ['nativewind/babel', { mode: 'compileOnly' }],
      'react-native-reanimated/plugin',
    ],
  };
};

```

**Comment by iamhaaamed** [comment] 2022-12-01 08:37
style is working for normal usage but when I use it with nativewind it's not working.
This is the normal usage of this library:
```
import * as React from 'react';
import type { IconProps } from 'react-icomoon';
import IcoMoon from 'react-icomoon';
import { Path, Svg } from 'react-native-svg';

import iconSet from './selection.json';

export const Icon = (props: IconProps) => (
  <IcoMoon
    native
    SvgComponent={Svg}
    PathComponent={Path}
    iconSet={iconSet}
    style={{ margin: 5 }}
    {...props}
  />
);
```

**Comment by marklawlor** [comment] 2022-12-06 04:19
@iamhaaamed NativeWind simply turns the className into a style prop. If that's not working, then you have a misconfiguration somewhere (eg like forgetting to include this file in your `content`) I would recommend either following the troubleshooting guide or providing a link to a repository that demonstrates the issue.

**Comment by marklawlor** [comment] 2022-12-12 23:43
Closing due to lack of information. If you can produce a reproduction I'll happily reopen

**Closed by marklawlor** 2022-12-12 23:43 UTC

**Comment by a-eid** [comment] 2023-01-24 13:21
@marklawlor Mark a similar issue, is that `styled` does not work with Icon from icon when used with `createIconSetFromIcoMoon`, I'm happy to create a reproducible example if need be.

**Comment by ningacoding** [comment] 2024-09-24 01:58
> @marklawlor Mark a similar issue, is that `styled` does not work with Icon from icon when used with `createIconSetFromIcoMoon`, I'm happy to create a reproducible example if need be.

please provide reproducible example, i'm facing same issue with `@expo/vector-icons`
