### ISSUE TITLE
Flash of incorrect color scheme when coming from background state.

### ISSUE THREAD

**Issue by JClackett** [marklawlor/nativewind#728] opened 2024-01-06 18:41 UTC
**Describe the bug**
When opening the app from the background state, I get a flash of the opposite color scheme. Not sure if this is an expo-router thing maybe? 

**To Reproduce**
Style any View with dark or light mode styles i.e. "bg-white dark:bg-black"

**Expected behavior**
Doesn't flash

**Screenshots**

https://github.com/marklawlor/nativewind/assets/12549124/32414484-4457-40b0-a462-d4c29e202921

**Additional context**

Im only using

```
// app config
userInterfaceStyle: "automatic",

// versons
"expo": "~49.0.21",
"expo-router": "2.0.14",
"nativewind": "2.0.11",
```

Standard tailwind + nativewind setup.

Any idea what could be causing this? have no idea whats going on, have a few projects using nativewind that don't do this, but can't figure out whats unique about this project. Has anyone ran into this before?

**Comment by marklawlor** [comment] 2024-01-15 12:07
Duplicate of #478

**Closed by marklawlor** 2024-01-15 12:07 UTC

**Comment by JClackett** [comment] 2024-01-15 15:09
Im using expo-router so the fix in the other issue doesnt really help, and also I get a flash of the opposite theme, not just flash of white when the theme is set to dark.

**Comment by JClackett** [comment] 2024-01-15 15:36
This solved temporarily for me

```ts
  const colorScheme = useColorScheme()
  const { setColorScheme } = useNWColorScheme()
  React.useEffect(() => {
    setColorScheme(colorScheme as "light" | "dark")
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [colorScheme])
```
