### ISSUE TITLE
v4: expo export / EAS build not working

### ISSUE THREAD

**Issue by solaldunckel** [marklawlor/nativewind#591] opened 2023-10-24 11:21 UTC
**Describe the bug**
`expo export` is failing if the native.css files is not already existing.
The native.css file is created but asynchronously (after the crash), so if I run it again it would work.
It also fails on EAS when building the app.

Using `4.0.0-alpha.26`

```
Error: Unable to resolve module /Users/sdunckel/Projects/timepilot/apps/mobile/global.css.native.css from /Users/sdunckel/Projects/timepilot/apps/mobile/global.css: 

None of these files exist:
  * global.css.native.css(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.svg|.native.svg|.svg|.android.cjs|.native.cjs|.cjs|.android.css|.native.css|.css)
  * global.css.native.css/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.svg|.native.svg|.svg|.android.cjs|.native.cjs|.cjs|.android.css|.native.css|.css)
> 1 | @tailwind base;
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 |
```

**To Reproduce**
1. Make sure the `node_modules/.cache/*.native.css` is deleted
2. Run `expo export --output-dir ./build --platform ios` or EAS build

**Additional context**
I've tried modifying the output in `withNativeWind` outside node_modules folder, it still doesn't work.
For EAS build I commit my *native.css file so it doesn't fail.

**Comment by surgeharb** [comment] 2023-10-24 14:57
Yes, I wanted to report this, for now you can add [this line](https://github.com/nodegram/nativeflare/blob/main/apps/expo-demo/package.json#L12) to your `package.json`

`"eas-build-post-install": "tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css.native.css"`

**Comment by solaldunckel** [comment] 2023-10-24 18:05
> Yes, I wanted to report this, for now you can add [this line](https://github.com/nodegram/nativeflare/blob/main/apps/expo-demo/package.json#L12) to your `package.json`
> 
> `"eas-build-post-install": "tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css.native.css"`

Thanks, much better than commiting the output file !

**Comment by marklawlor** [comment] 2023-10-28 01:59
Can people please reset their cache and try the latest version of the alpha. 

If you are still having this issue, I would appreciate some assistance in troubleshooting it, as this line should block Metro's startup until the necessary files are generated

https://github.com/marklawlor/nativewind/blob/d8420c101fd9db9372d02895786a13ec4bb3f7b9/packages/nativewind/src/metro/index.ts#L109

`tailwindCli` is an Promise that only resolves once the Tailwind CLI has output the line `Done In`. Tailwind CLI generates the `.css` file, so we expect the file to exist at this stage.

Things I am interested in:
 - When we resolve the `tailwindCli` deferred, does the file always exist on the file system?
 - Is there a metro configuration where `getTransformOptions` isn't blocking?
 - Is there a logic error I've missed ? E.g the transform is pointing to a different output to the file being generated

**Comment by marklawlor** [comment] 2023-10-31 13:00
Metro collects the files as it transforms (as a transformer may inject a require or import statement). Can you please verify for me that you are using the latest version of the alpha (`4.0.0-alpha.31` at time of writing). Can you verify this by checking the version inside `node_modules/nativewind/package.json`. 

I suspect you may be using a carat `^` in your `package.json` which will not work for prerelease versions. You maybe running an older version, even if your `package.json` has a higher version (as all prereleases are equal, so it won't upgrade)

**Comment by surgeharb** [comment] 2023-10-31 15:25
Just had the chance to try it today, build seems working locally after upgrading to `alpha.31` and without `eas-build-post-install` in the `package.json`. Thanks!

One observation, it seems that the build is using the temp folder for the css, and not relying on the `.cache/nativewind/...` which I guess that this is the expected behavior.

<img width="397" alt="Screenshot 2023-10-31 at 16 22 52" src="https://github.com/marklawlor/nativewind/assets/22060043/573e12f1-8e8f-458b-bbc1-b18d800d6ee6">

**Comment by solaldunckel** [comment] 2023-10-31 17:41
It's also working for me now !

I just had to remove this in my `metro.config.js`

```diff
const config = getDefaultConfig(projectRoot, {
  isCSSEnabled: true,
});

-- config.cacheStores = [
--  new FileStore({
--   root: path.join(projectRoot, "node_modules", ".cache", "metro"),
--  }),
-- ];
```

**Comment by marklawlor** [comment] 2023-11-01 01:06
@solaldunckel You should be able to use `FileStore`, that simply just changes where Metro keeps its cache. So by removing it, its the same as clearing your cache.

You should be able to re-add that to your config, clear your cache and rebuild again. Altho I would recommend against keeping a per project cache as one of the advantages of Metro is being able to share its build cache across multiple projects.

This appears to be resolved so I'm going to close the issue.

**Closed by marklawlor** 2023-11-01 01:06 UTC

**Comment by matallui** [comment] 2024-02-08 23:02
@marklawlor I'm hitting this issue withe 4.0.23 and the latest Expo SDK 50. I also have the `config.cacheStores` set because if I don't I run into an issue where the metro resolver starts following an entrypoint for a different Expo app in the same monorepo. Adding this was the only way I found to work around that issue.

This issue happens when I run `npx turbo dev --parallel` in my monorepo and I do have 2 Expo apps, so I'm getting the feeling that metro is just struggling to operate with this setup.

Any suggestions or ideas?

**Comment by DeluxeOwl** [comment] 2024-02-20 13:53
My issue was that the tailwind command would time out after 70 seconds (the default is 60), and I think it picked up `node_modules`...

I changed my `tailwind.config.js` from this:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
	// NOTE: Update this to include the paths to all of your component files.
	content: ["./**/*.{js,jsx,ts,tsx}"],
	presets: [require("nativewind/preset")],
	theme: {
		extend: {},
	},
	plugins: [],
};
```
to this (added `src`):
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
	// NOTE: Update this to include the paths to all of your component files.
	content: ["./src/**/*.{js,jsx,ts,tsx}"],
	presets: [require("nativewind/preset")],
	theme: {
		extend: {},
	},
	plugins: [],
};
```

**Comment by bnussman** [comment] 2024-04-30 04:48
This is still an issue on `4.0.36` and it was never fixed in `alpha.31` as far as I can tell

My use case is running `expo start --web` in CI so I can run Playwright tests against my app.

![Screenshot from 2024-04-30 00-44-20](https://github.com/marklawlor/nativewind/assets/6440455/6d46de00-414a-42b1-ac8c-3b1c4c69f63b)

**Comment by rhutikcodes** [comment] 2024-05-27 18:23
how to fix this issue? i checked all the other related github issues, none of which is working -_-

**Comment by NigelBreslaw** [comment] 2024-07-11 20:48
Adding this script to the package.json and running it before a build seems to work `"postinstall": "npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css"`

**Comment by carloscurcino** [comment] 2024-07-12 20:07
Hi, I'm still having this error even adding the postinstall to the scripts on package.json. The error is happening on eas build, I'm building an apk. Anyone knows how to solve??

**Comment by focux** [comment] 2024-07-12 20:34
> Adding this postinstall to the package.json which will run automatically after the install seems to fix it`"postinstall": "npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css"`

That worked for me. Thank you.

**Comment by carloscurcino** [comment] 2024-07-12 20:37
> > Adding this postinstall to the package.json which will run automatically after the install seems to fix it`"postinstall": "npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css"`
> 
> That worked for me. Thank you.

What version are you using??

**Comment by focux** [comment] 2024-07-12 20:39
I'm using `^4.0.1` and I was trying to build the project for web. Make sure that the path of the global file input, matches yours.

**Comment by carloscurcino** [comment] 2024-07-15 12:15
Installing the 4.0.35 version of nativewind worked for me

**Comment by riteshreg** [comment] 2024-08-22 07:16
> "eas-build-post-install": "tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css.native.css"

where to add this in package.json

**Comment by riteshreg** [comment] 2024-08-22 07:38
> Installing the 4.0.35 version of nativewind fixed it for me

this works for me

**Comment by PetrusBorges** [comment] 2024-08-26 14:46
> Installing the 4.0.35 version of nativewind fixed it for me

This works for me, thanks a lot 👍

**Comment by jancbeck** [comment] 2024-09-02 12:26
I was on 4.0.36 and downgrading didn't help. Adding the post-install script did.
I'm using pnpm and turorepo and the error only showed when creating an expo web export.

**Comment by doulgs** [comment] 2024-09-27 14:28
> Instalar a versão 4.0.35 do nativewind resolveu o problema para mim

I want to give a huge thank you to @carloscurcino  for sharing that amazing tip that saved my project! Thanks to your post, I was finally able to generate the build that had been stuck for days
