### ISSUE TITLE
V4:  Fast Refresh is inconsistent

### ISSUE THREAD

**Issue by ShaneKeney** [marklawlor/nativewind#661] opened 2023-11-21 19:17 UTC
**Describe the bug**
Adding new utility classes during development does not consistently reflect changes.  Reloading does not correct it either.  I have to kill the development server and reopen the app.

Is there a configuration option to address this?  Is this supposed to be the behavior?

Occurs on both Expo Go & Expo custom development client.

The correct styling is reflected after closing the development server and restarting the server via `npx expo start -c` and reopening the dev client.

**Expected behavior**
Adding utility classes in the `classNames` field of a component should "Fast Refresh" and reflect the changes without requiring the developer to close the 

**Screenshots**
e.g. of usage:

```
<View className={'flex max-w-screen-lg flex-1 items-center justify-center gap-3'}>
     ...
</View>
```

Screen shown when dev client first started and running:

![image](https://github.com/marklawlor/nativewind/assets/53321733/aff3ca19-3e1c-4c19-85b1-ac78858d59f9)

Changing `gap-3` to `gap-5` while development server is running:  

![image](https://github.com/marklawlor/nativewind/assets/53321733/7e9b88be-6ead-41b4-aa64-88a6a428f375)

You can see the gap class utility is completely ignored now.
Stopping the development server.  Re-run `npx expo start -c --dev-client`

![image](https://github.com/marklawlor/nativewind/assets/53321733/e314c687-eada-4aa1-80ed-ec8507db9d03)

`gap-5` is now accurately reflected.

Conclusion?

There seems to be an issue with the Live Reloading feature when it comes to the tailwind class utilities.  This may just be a configuration issue on my part but reading through the docs I can't find anything specifically that would indicate why that would be.

**Comment by GustavoBonfimS** [comment] 2023-11-22 00:23
Related to #643 and #653 . It is a bug in Metro cache and will be fixed in a future release of Expo

**Comment by ShaneKeney** [comment] 2023-11-22 15:06
Is there any rough ETA on when this will occur?

**Comment by marklawlor** [comment] 2023-11-23 04:50
This might be fixed in `4.0.14`. If you'd like an ETA can you please provide a production, as it maybe a configuration issue or something else. Screenshots provide very minimal value when troubleshooting code

**Comment by ShaneKeney** [comment] 2023-11-23 06:49
@marklawlor I'll try upgrading to 4.0.14 first.  If I am still having issues I'll create a public project with the symptoms.  I would have done that sooner but I am in a project I can't share publicly.  But I'll remove the pieces I can't share and create a reproducible example if I continue to run into issues.

**Comment by ShaneKeney** [comment] 2023-12-07 21:49
@marklawlor Here is a templated project I have created that shows the above issue after upgrading to `4.0.14`.   It occurs both in Expo Go and Custom Development Client.

You can see this by going to `app/(aut)/index.tsx` and changing the following:
```
        <Text className={'text-6xl font-bold text-lightTextTheme dark:text-darkTextTheme'}>
          Examples:
        </Text>
```

to

```
        <Text className={'text-6xl font-bold bg-red-500'}>
          Examples:
        </Text>
```

Change is not reflected even though the client shows the app has "Refreshing..."

**Comment by garygcchiu** [comment] 2023-12-15 00:54
I'm running into a related issue where if I change my theme's colours (located in a `colors.js` that is imported into `tailwind.config.js`), I have to restart the metro bundler + restart the app to see the changed color. However, the colour in the autocomplete would still show the old colour, and I'm not sure how to get the autocomplete to "refresh" with my updated theme colour.

**Comment by ShaneKeney** [comment] 2023-12-21 02:34
> @marklawlor Here is a templated project I have created that shows the above issue after upgrading to `4.0.14`. It occurs both in Expo Go and Custom Development Client.
> 
> You can see this by going to `app/(auth)/index.tsx` and changing the following:
> 
> ```
>         <Text className={'text-6xl font-bold text-lightTextTheme dark:text-darkTextTheme'}>
>           Examples:
>         </Text>
> ```
> 
> to
> 
> ```
>         <Text className={'text-6xl font-bold bg-red-500'}>
>           Examples:
>         </Text>
> ```
> 
> Change is not reflected even though the client shows the app has "Refreshing..."

@marklawlor Just realizing that I didn't ever link the actual repo that I created as a template:  https://github.com/rally2/exporouter-nativewind .  

Happy Holidays!

**Comment by pencilcheck** [comment] 2023-12-30 02:25
I hope this is fixed soon. I also experience this issue with EAS and on Expo SDK 48 and using nativewind v4

**Comment by josetr** [comment] 2024-02-01 04:02
It's even worse using react-native-windows. Even tho the generated css file in the cache folder is updated correctly always, the change is not reflected 99% of the time. A full metro server restart is required.

Steps to reproduce
```
npx react-native init myproject
npx react-native-windows-init --overwrite
# install NativeWind v4
npx react-native run-windows
```

Then try to create a component using `bg-red-400` for example, which won't work, until you re-save global.css, and restart the metro server.

The experience is terrible.

**Comment by Mondmarmelade** [comment] 2024-02-01 16:21
I have to agree with @josetr. A fix is really necessary.

**Comment by Fynn** [comment] 2024-02-03 13:57
Any updates on this? It's a really bad DX

**Comment by minhnc** [comment] 2024-02-04 00:08
It seems to be fixed with latest nativewind 4.0.23.

**Comment by Fynn** [comment] 2024-02-04 01:15
@minhnc For me its still not working in version 4.0.23

**Comment by Mondmarmelade** [comment] 2024-02-04 08:39
Version 4.0.23 didn't fixed it for me either.

**Comment by minhnc** [comment] 2024-02-04 22:31
Working fine for me. Im with MacOS btw. Do you mind sharing a sample project?

**Comment by ShaneKeney** [comment] 2024-02-05 17:24
@minhnc Sample project linked above in my comment.  When I add `!bg-red-500` as an override, there is no refresh to reflect the changes.

**Comment by minhnc** [comment] 2024-02-11 07:57
@ShaneKeney hope this helps ( cloned your sample project )

[![demo](https://img.youtube.com/vi/yGqUdr2cuTU/0.jpg)](https://youtu.be/yGqUdr2cuTU)

**Comment by ShaneKeney** [comment] 2024-02-11 14:31
@minhnc Thanks.  I took a look and noticed your running this on MacOS.  I think this is an issue isolated to when leveraging WSL2.  I have my Macbook where this issue does not happen but on my PC running WSL2 it does.

**Comment by marklawlor** [comment] 2024-02-13 03:20
Please try `4.0.26`. The dev server was reworked to hook into the existing FastRefresh HTTP server.

**Comment by ShaneKeney** [comment] 2024-02-16 21:43
@marklawlor Thank you!  It is looking like the issue has resolve itself with the update to `4.0.26`.  I'll continue to test it out but the initial example using `!bg-red-500` that was not working is now fixed which is a sign in the right direction.
Thanks for all the hard work!

**Comment by marklawlor** [comment] 2024-02-19 02:02
Closing issue, if your still experiencing this issue please open a new ticket

**Closed by marklawlor** 2024-02-19 02:02 UTC
